name: Sync Debian

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and tag image
        run: |
          docker pull docker.io/debian:trixie
          docker tag docker.io/debian:trixie ghcr.io/vansour/debian:trixie

          docker pull docker.io/debian:trixie-slim
          docker tag docker.io/debian:trixie-slim ghcr.io/vansour/debian:trixie-slim

      - name: Push image
        run: |
          docker push ghcr.io/vansour/debian:trixie
          
          docker push ghcr.io/vansour/debian:trixie-slim