name: Sync Rust

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull and tag image
        run: |
          docker pull docker.io/rust:trixie
          docker tag docker.io/rust:trixie ghcr.io/vansour/rust:trixie

      - name: Push image
        run: |
          docker push ghcr.io/vansour/rust:trixie